### ISSUE TITLE
Same-piece tetris

### ISSUE THREAD

**Issue by licht1stein** [qntm/hatetris#3]
I was only getting the same piece over and over again. It sure spoils the game, but where's AI in that?

![image](https://user-images.githubusercontent.com/35418634/72171945-a149a000-33dc-11ea-8a2b-c5997dada0bc.png)

**Comment by qntm** [comment]
If it was really giving you the same piece every time you would be able to get infinite lines. See if you can figure out how! Once you've worked that out, you'll see other pieces appear.
