### ISSUE TITLE
Pieces invisible when night light is on

### ISSUE THREAD

**Issue by alvitawa** [qntm/hatetris#53]
If you have night light on (blue light filter), then the blue pieces become completely invisible.

**Comment by qntm** [comment]
What do you mean by "blue light filter"? Is this an app you're usng? Can you share a screenshot?

**Comment by alvitawa** [comment]
Night light is a windows feature, but maybe you have heard of f.lux or redshift. Gnome also has it. It makes your screen look 'redder' by filtering out blue light which helps with falling asleep in the evening. So since the pieces are pure blue, if you have night light configured at a high intensity they become invisible. It took me a while to figure out why they where disappearing when you place them :p

https://recordit.co/87P45GGGiv

Simple solution: Just don't use pure blue pieces, although most people probably have the filter at a much lower intensity than me so they would still see the pieces faintly.

**Comment by qntm** [comment]
Hah amazing. Have reproduced this locally. The pieces only disappear at around intensity 75. I'll see what the simplest approach here is...

**Comment by qntm** [comment]
Live version is updated with the fix.
