### ISSUE TITLE
Redesigned AI API

### ISSUE THREAD

**Issue by CodeLikeCrazE** [qntm/hatetris#67]
I think that a safer way that you could rewrite the AI API is like this:

- Append AI API function declarations to the beginning of inputted code
- Convert modified code into JS data URI.
- Start web worker from JS data URI.
- Post a message to the web worker when it needs to calculate a move.
- Make the web worker post a message to the host script to send the result.

The reason you can't just use a URL to some script that evals the AI code is that web workers can still run fetch requests, so you don't want to eval code on the main HATETRIS domain.

**Comment by qntm** [comment]
Can you clarify what is safer about this approach?

**Comment by CodeLikeCrazE** [comment]
> Can you clarify what is safer about this approach?

Webworkers are isolated from the main script, so anything evalled is basically sandboxed, and since it is a data uri, it is not on one specific domain, so it cannot run fetch requests.

**Comment by qntm** [comment]
I will consider making the change you've suggested. But in this scenario the user is, for some reason, intentionally attacking themself. I don't really think there's a lot we can do to protect them from that. There's nothing stopping them from opening up the browser tools, for example, and pasting their malicious code there instead.

**Comment by CodeLikeCrazE** [comment]
> I will consider making the change you've suggested. But in this scenario the user is, for some reason, intentionally attacking themself. I don't really think there's a lot we can do to protect them from that. There's nothing stopping them from opening up the browser tools, for example, and pasting their malicious code there instead.

It just makes it safe enough that the user can safely post any code into the AI field, I know that it is impossible to protect people from being malicious to themselves.

**Comment by Storyyeller** [comment]
There are almost certainly ways to cause mischief from inside a web worker, and it's best not to give people a false sense of security.

**Comment by CodeLikeCrazE** [comment]
> There are almost certainly ways to cause mischief from inside a web worker, and it's best not to give people a false sense of security.

How can webworkers be attacked?

**Comment by qntm** [comment]
Spent some time today looking at the feasibility of this... It seems pretty thorny. Shifting all the logic out to worker is annoyingly difficult because of just how much logic there actually is and how much information needs to be sent around, most of it functions... stringifying all the API code into a data URI is also turning out to be quite annoying. All this to prevent a security issue which I can't say I much care about, for reasons I already mentioned...

Thank you for the suggestion.
