### ISSUE TITLE
Tetris papers

### ISSUE THREAD

**Issue by wyattscarpenter** [qntm/hatetris#71]
I've recently come across two papers that might be relevant to this project and/or https://github.com/qntm/tetris

The first purports to show an algorithm in which the machine can force you to lose a game of tetris: 
[Can you win at TETRIS? Brzustowski, John 1992](https://github.com/qntm/hatetris/files/6644050/can.you.win.at.tetris.brzustowski.john.1992.pdf)

The second purports to show that a series of SZSZSZ... is enough, though it seems to be slower: 
[How to lose at Tetris. Burgiel, Heidi 1997](https://github.com/qntm/hatetris/files/6644054/how.to.lose.at.tetris.heidi.burgiel.mathematical.gazette.1997.pdf)

**Comment by qntm** [comment]
Thank you for the information. I'm aware of both of those papers. It's well-known that an adversarial AI can force the player to lose eventually. The question is how many lines the player can make before losing. In the second paper, for example, it's stated that the game ends "before 70,000 tetrominoes have been played" - which is about 28,000 lines. This is not a very impressive upper bound. At present, our best AI allows at most 31 lines, which isn't proven as such, but is clearly a practical improvement in terms of how much tougher the game is.

I'm almost certain that we can't lower that bound to 0, but I think we can definitely go lower than 31 lines. Additionally, I am less interested in assembling a formal proof of a bound than I am in making a game which is harder to play for humans.

**Comment by wyattscarpenter** [comment]
I'm glad you are aware of this!

Additionally, you've inspired me to dig into Brzustowski's thesis and try to understand how many line clears it can force the player down to. Correct me if I'm wrong, but I think it's supposed to be approximately equal to the well depth, as each clear produces a shield against the other type of kink, which is then supplied. So, I think this would provide an upper bound of 21, which is better than the current HATETRIS bound of 31. However, I'm not a tetris wiz, so it's possible there's some trick I've missed!

Here is my implementation of Brzustowski's algorithm

[kinks.js.txt](https://github.com/qntm/hatetris/files/6644526/kinks.js.txt)

Here are screenshots of my last two pieces, achieving score 21:

![image](https://user-images.githubusercontent.com/27367056/121820096-c2c15200-cc88-11eb-8095-28f79d25e797.png)
![image](https://user-images.githubusercontent.com/27367056/121820117-d2d93180-cc88-11eb-88a7-3da97319625c.png)

**Comment by qntm** [comment]
With your first AI, I got 29 lines on my first attempt:

![image](https://user-images.githubusercontent.com/1735353/121821865-b098e100-cc93-11eb-977e-f6109887f240.png)

...But on closer inspection, I believe what you've actually done is successfully exposed a bug in my "custom AI" functionality. You see, HATETRIS has undo/redo functionality. But althought this works fine with the basic HATETRIS AI, which is purely deterministic and has no internal state, your AIs have persistent internal state *which is not undone when I press Ctrl+Z*. (How could it be?) This means I can land a piece, undo until the piece despawns, then try again, and the AI will spawn a different piece which its logic should not allow to be possible.

I will need to think about what to do about this. Lowering the upper bound from 31 to 20-ish is an improvement...

**Comment by qntm** [comment]
I think probably the solution to the bug I just mentioned is to make it so that

1. when the AI function returns a piece ID, it can optionally also return an immutable state object, which is kept as part of the replay frame
2. when we call the AI function with the current well state, we also pass an argument which is the state object associated with that frame.

The AI function must then be a pure function of both the well state and its own previous state. When we undo to prior replay frames, we also undo to prior AI function states. The AI must be pure and deterministic, and neither maintain its own internal state nor modify the state object passed to it.

This will break any existing AI functions but I think there probably aren't too many of those.

(A future update to HATETRIS will take advantage of this functionality, to prevent infinite looping.)

**Comment by wyattscarpenter** [comment]
Yeah, that seems like the best way for it. I tried to figure out how to clone closures in javascript but I don't think it's possible.

On the bright side, if you make this change and specify `the AI must be pure and deterministic`, you should be able to provide replays for custom AIs!

**Comment by qntm** [comment]
The most recent changes under #75, #76 and #77 now mean that the AI API has been updated in the way I described. The README documents these new changes.

**Comment by wyattscarpenter** [comment]
Excellent! I've reimplemented the two AIs above in the new format, it seemed to work well. Let me know what you think of them, at your leisure.

[kinks-immutable.js.txt](https://github.com/qntm/hatetris/files/6683716/kinks-immutable.js.txt)

[kinks2-immutable.js.txt](https://github.com/qntm/hatetris/files/6683717/kinks2-immutable.js.txt)

**Comment by qntm** [comment]
Excellent!

OK so what I'm going to do is add Brzustowski's Algorithm 2 to the list of available AIs. I think that algorithm is of sufficient historical significance that it's worth having it in the repertoire, and I like that it has a relatively low guaranteed score ceiling compared to HATETRIS (which, if you didn't notice, is at 41 now). I notice you did a simplification to account for the fact that HATETRIS doesn't have a "preview piece" but what I'll probably do is provide a version *with* a preview piece... just store it internally as unseen state. Or possibly both versions.

Is it okay if I modify your implementation to use more idiomatic JavaScript? I will eliminate the `JSON.parse(JSON.stringify(...))`, convert `togglePiece` to a ternary expression, and suchlike.

**Comment by wyattscarpenter** [comment]
Very good! Yes, please feel free to modify my code as you wish. Further, I hereby formally release all of my code in this thread into the public domain under [CC0](https://creativecommons.org/publicdomain/zero/1.0/legalcode), so you can do whatever you like with it, and I also hereby formally release said code under your current project license for good measure.

The "Algorithm 1" (page 32) in the paper is insignificant to proper Tetris so I think calling this AI "Brzustowski" would be unambiguous and succinct. Also, implementing the supply of the preview piece feature shouldn't change the score the user can achieve—Brzustowski seems to prove this on page 45—so it's probably best, as you intuit, to supply that if one can be bothered to implement it.

Finally, I'm very curious to know if you think the Brzustowski algorithm really does only allow 21 lines—and furthermore if kinks2 only allows 7.

**Comment by qntm** [comment]
Alright, under #78 I have added Brzustowski's AI to the HATETRIS repertoire and it is now [available to play against](https://qntm.org/files/hatetris/hatetris.html).

That's the good news! The bad news is that contrary to what I said earlier, this AI doesn't set a ceiling anywhere near 21 lines. On my first attempt I was able to get 55:

> ౚටฅٽ௨෨ଈݚСචƘݷౚ೯ບߢ௨චÐݺɷගÐݚɷ౾ܖࠆಛقຽঅ௩قଭݪ௧ڠଭɟ௨ගɑݸ౻ටПݹ౻ඪܖࢭࢶටະऔ௨ชІݶಒටତݹ௮੬ໃए௨ඩషݹࢳΟໃঅ௩Ϻසݶ౻ටลɒƐปໄஈб೯ܘމலڄໃѣҳబຽࢭ௧پܖࠇமقܬݶసطДݺஶϺ༠ɖɷڠПݚݫට༨অ௩Ѳໃףذචʃݹ୦Ѹໃɠ௨ಀІݪɷలฅהԥೱ൧ݺذගІܭϟقܯஈলටݕݺɷඪ൧ރ௧ڠໞݶಏكɑקযඤʃܭدڠЖܭИටКђ௬ට༠ݹଛʈໄຍ௩Ϻໄຍஶشܙਨ௩ѸແࡨߛࡆІܭЬقଚԓஶѮໄຍ४ΟฦݶƖقФ୬௧ٴະࡆذ౾ಊݪСඦബঅࢴඥܨІةɤໃקਙชІࢭরइໄЅЗࡄฅݹઽඨƞݷసقʃࢭࠒΟฆݹߝɈฅђߝԚໄŦ௬ॴ༠הభ൝Іࢭஜу༨ঀಇΘuঅఴуଞݺد෪ງڝࢶ੬ПܭɷٯฦݚСಀഫɟஜضÐɝɴฃ༥މభ෨ܐঔਆ

(Remember to select the right AI before playing the replay back.)

The variant with instantaneous toggling may be slightly tougher, and the variant which switches between S and Z on every line made might be tougher still... but I will look further into this later.

**Comment by wyattscarpenter** [comment]
Ah, I see, very interesting, thanks!

**Comment by qntm** [comment]
Under #80 I have also added Heidi Burgiel's AI to the HATETRIS repertoire.

**Comment by wyattscarpenter** [comment]
Update: I asked knewjade what he could make of kinks2-immutable.js.txt and his search program found this infinite loop:

`۳ටฅཧ௩Οໃɚ௨ඖ༱ݹࢳقໄஈஹปແঅ௩ƣໃɡ௨ඩໃݟ௨ඖІݺذඨІݪޛඨÐݹҋටଠݹ௰ටତݹ௫ටມঅஶϺໃঅஶҔໃࠇ௨৭ໃס௨ණໃף௨ඩܘݱಳඤɑݹಳඤʑݹభටഋݹષට໐ݹસටໄђஹปແࢭ௨ปແऔ௨සໃڮ௨൝ܘݺ௨൝ໃݺ௨ಅແঅࢸ൞ฆ2`

**Comment by qntm** [comment]
Wow, that's amazing! I had no idea that the extra piece of delay was so crucial to this algorithm. I'm glad we decided to preserve it in the end. For my own future reference, this is a 5-piece/2-line loop, the shortest possible in Tetris. To produce the loop...

1. Land the first 6 S pieces as follows, producing a line:

![kj1](https://user-images.githubusercontent.com/1735353/126875743-06b798b8-a3dc-4b8a-a022-9aeb44ee8d31.png)

2. Land the next 3 Z pieces as follows, producing a second line:

![kj2](https://user-images.githubusercontent.com/1735353/126875765-4e04c06b-cc0c-4850-87af-535b77ef2684.png)

3. Land the next 2 S pieces as follows, producing a third line:

![kj3](https://user-images.githubusercontent.com/1735353/126875778-658cf848-e534-4a8e-bedc-f3c01ebd5930.png)

4. Land the next 4 Z pieces as follows, producing a fourth line:

![kj4](https://user-images.githubusercontent.com/1735353/126875818-b1d4ec01-aedb-432e-9210-fa45c0b729a2.png)

5. Land the next 2 S pieces as follows, producing a fifth line:

![kj5](https://user-images.githubusercontent.com/1735353/126875839-26930ea4-d3d2-473e-99e9-67a3b663547e.png)

6. Go back to step 4. You will find you only need to land 3 Z pieces, not 4, to reach the same well again and begin the loop.

The loop looks like this:

![kjloop](https://user-images.githubusercontent.com/1735353/126876425-f5534b46-849d-4743-b9ca-eb8d382bf1f7.png)

**Comment by wyattscarpenter** [comment]
I hypothesize that the crucial feature missing from kinks2-immutable.js.txt is cycle-detection, not the one piece delay, but it would be interesting to see what knewjade's software, https://github.com/knewjade/solution-finder, would make of the other mutations of Brzustowski's Algorithm (original, original without "preview" piece, kinks2-immutable.js.txt with "preview" piece). I did not pursue this at this time because I don't know enough Japanese to understand that software, and I would feel kind of awkward asking knewjade to run more analyses for me.

**Comment by qntm** [comment]
Oh, right, like a fool I forgot that kinks2-immutable.js wasn't actually Brzustowski's algorithm or anything like it...

**Comment by wyattscarpenter** [comment]
Further update: I asked knewjade to look at the original Brzustowski algorithm / kinks-immutable.js.txt but apparently the program he uses to investigate these things can't detect cycles so he didn't get anywhere.
