### ISSUE TITLE
Python version piece generation algorithm or pseudocode

### ISSUE THREAD

**Issue by PttCodingMan** [qntm/hatetris#74]
Hi I am a researcher, but I am not familiar with javascript.
If you don't mind, I hope I can get the pseudocode or python code of the algorithm.
This can help me understand the algorithm.

Love this game!

**Comment by qntm** [comment]
Hi, I'm sorry but no, I am not going to port the HATETRIS algorithm from JavaScript to Python for you. [Here is the JavaScript algorithm](https://github.com/qntm/hatetris/blob/main/src/enemy-ais/hatetris-ai.ts).
